---
- name: User configuration
  hosts: all
  become: true
  vars_files:
    - user_list.yml
    - secret.yml
  tasks:

    - name: Create users whose uid start with 1 on webservers host group
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        group: wheel
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}" 
      when: item.uid is match("^1") and inventory_hostname in groups['webservers']

    - name: Create users on database host group
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        group: wheel
        shell: /bin/bash
        password: "{{ database_password | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"
      when: item.uid is match("^2") and inventory_hostname groups['database']

    - name: upload ssh key to users
      ansible.posix.authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      loop: "{{ users }}"
      when: (item.uid is match('^1') and inventory_hostname in groups['webservers']) or (item.uid is match('^2') and inventory_hostname in groups['database'])

